### ISSUE TITLE
cannot download the smpl model from the provided link

### ISSUE THREAD

**Issue by pramishp** [hanabi7/VoteHMR#2]
Thank you for the code but the baidu link is not working https://pan.baidu.com/s/19D4WGM1-bhRR-06iAO5l_A.
The link takes to a page but the download option from that page downloads baidu network software but not the smpl models.

**Comment by hanabi7** [comment]
the link above contains several models needed for the training including the smpl models

**Comment by pramishp** [comment]
![Screenshot from 2022-06-23 15-52-51](https://user-images.githubusercontent.com/15194546/175274892-de8206f4-05e2-485f-b701-f82d6dd43c59.png)
It shows this. The extraction fails and I am not able to download the models.

**Comment by hanabi7** [comment]
please letme know your email address and i can send this file to you, besides, i will upload a google drive version afterwards.

**Comment by pramishp** [comment]
My mail address is 076BCT047.pramish@pcampus.edu.np @hanabi7

**Comment by DavidBoja** [comment]
could you also send me the data as well? -- if you haven't uploaded it already to Google Drive or somwhere else.

Thank you in advance,
David
